[package]
name = "boa-wasi"
version = "0.1.0"
authors = ["Tomas Olvecky <tomas.olvecky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Boa = { path = "crates/boa/boa" }
